apiVersion: v1
kind: Service
metadata:
  name: container2-service
spec:
  selector:
    app: kubernetes-image2
  type: ClusterIP
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8000
