apiVersion: v1
kind: Service
metadata:
  name: container1-service
spec:
  selector:
    app: kubernetes-image1
  type: LoadBalancer
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 6000
